name: 'Universal actions'
description: 'Common actions to be called by github actions to deploy apps'
runs:
  using: composite
  steps:
  - name: Start minikube
    id: minikube
    uses: medyagh/setup-minikube@master
  - name: Enable Ingress
    run: minikube addons enable ingress
    shell: bash
  - name: Create k8s objects via their yml files
    run: |
      alias k="kubectl"
      kubectl apply -f service/k8s-manifests/namespace.yml 
      kubectl apply -f service/k8s-manifests/deployment.yml
    shell: bash
  - name: Check Resources
    run: |
          kubectl get po
          kubectl describe po
          kubectl describe po -n reference-service-showcase
    shell: bash