name: 'Universal actions'
description: 'Common actions to be called by github actions to deploy apps'
runs:
  using: composite
  steps:
  - name: Start minikube
    id: minikube
    uses: medyagh/setup-minikube@master
  # - name: Enable Ingress
  #   run: minikube addons enable ingress
    # shell: bash
  - name: Deploy K8s resources
    run: make deploy-resources
    shell: bash
  - name: Check Resources
    run: |
          kubectl get po -n reference-service-showcase
    shell: bash
  - name: Test App
    run: |
          echo "MINIKUBE_IP=$(minikube ip)" >> $GITHUB_ENV
          curl $MINIKUBE_IP:30007/service/hello
    shell: bash